services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apartments
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d apartments"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: { context: ./api, dockerfile: Dockerfile }
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/apartments?schema=public
      PORT: 4000
    depends_on:
      db: { condition: service_healthy }
    ports: ["4000:4000"]


  web:
    build:
      context: ./web/apartments-app
      dockerfile: Dockerfile
      args:
       NEXT_PUBLIC_API_BASE: http://localhost:4000
       INTERNAL_API_BASE: http://api:4000
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE: http://localhost:4000
      INTERNAL_API_BASE: http://api:4000
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
